create database sales_analytics;
use sales_analytics;

select * from sales_pipeline limit 5;
describe sales_pipeline;
describe sales_teams;
describe products;
describe accounts;

# converting the date columns in pipeline table to date
CREATE TABLE sales_pipeline_clean AS
SELECT
    opportunity_id,
    sales_agent,
    product,
    account,
    deal_stage,
    STR_TO_DATE(NULLIF(engage_date, ''), '%m/%d/%Y') AS engage_date,
    STR_TO_DATE(NULLIF(close_date, ''), '%m/%d/%Y') AS close_date,
    CAST(NULLIF(close_value, '') AS DECIMAL(12,2)) AS close_value
FROM sales_pipeline;

select * from sales_pipeline_clean;

# 1. How many deals are there at each stage of the sales pipeline?
# and what is the total and average deal value at each stage?
select deal_stage, count(opportunity_id) as number_of_deals, avg(close_value) as average_deal_value,
sum(close_value) as total_deal_value
from sales_pipeline_clean
group by deal_stage;

# 2. What percentage of all deals have been won?
select 
round(
	100.0*sum(deal_stage='Won')/count(*), 3
) as win_percent
from sales_pipeline_clean;

# 3. Which sales agents have generated the most revenue from Won deals?
select sales_agent, sum(close_value) as total_revenue
from sales_pipeline_clean
where deal_stage='Won'
group by sales_agent 
order by sum(close_value) desc;

# 4. Which products generate the most revenue?
select product, sum(close_value) as total_revenue
from sales_pipeline_clean
group by product
order by sum(close_value) desc;

# 5. Which 10 accounts have generated the most revenue?
select account, sum(close_value) as total_revenue
from sales_pipeline_clean
group by account
order by sum(close_value) desc
limit 10;

# 6. How many days does it take, on average, to close a Won deal?
select avg(datediff(close_date, engage_date)) as avg_days
from sales_pipeline_clean
where deal_stage='Won';

# 7. Which sales agents have the highest average deal value?
select sales_agent, avg(close_value) as avg_deal_value
from sales_pipeline_clean
where deal_stage='Won'
group by sales_agent
order by avg(close_value) desc;

# 8. Which products have the highest win rate?
select product, 
round(
100.0*sum(deal_stage='Won')/count(*), 3
) as win_rate
from sales_pipeline_clean
group by product
order by round(
100.0*sum(deal_stage='Won')/count(*), 3
) desc;

# 9. Which accounts are associated with the most opportunities, 
# regardless of whether they were won?
select account, count(opportunity_id) as total_opportunities
from sales_pipeline_clean
group by account
order by count(opportunity_id) desc;

# 10. How much revenue is generated by each sector?
select a.account, sum(close_value) as total_revenue
from accounts as a inner join sales_pipeline_clean as sp
on a.account=sp.account
group by a.account;

# 11. Which office locations generate the most revenue?
select regional_office, sum(close_value) as total_revenue
from sales_teams as st inner join sales_pipeline_clean as sp
on st.sales_agent= sp.sales_agent
group by regional_office
order by sum(close_value) desc;

# 12. For each sales agent, how many total opportunities do they handle, 
# how many have they won, and what is their win rate?
select sales_agent, 
count(opportunity_id) as total_opportunities, 
round(
100.0*sum(deal_stage='Won')/count(*), 2
) as win_rate
from sales_pipeline_clean 
group by sales_agent
order by 
round(
100.0*sum(deal_stage='Won')/count(*), 2
) desc;

# 13. How has Won revenue changed over time?
select year(close_date) as year, month(close_date), sum(close_value) as total_revenue
from sales_pipeline_clean 
where deal_stage='Won'
group by year(close_date), month(close_date)
order by month(close_date);

# 14. Which sales agents take the longest/shortest time to close Won deals?
select sales_agent, avg(datediff(close_date, engage_date)) as avg_days
from sales_pipeline_clean
group by sales_agent
order by avg(datediff(close_date, engage_date)) asc;

